/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[8] = {11, 1, 0, 4, 1, 2, 3, 4};
static const casadi_int casadi_s5[3] = {1, 0, 0};

/* Translational_drone_constr_h_fun_jac_uxt_zt:(i0[6],i1[5],i2[],i3[])->(o0,o1[11x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+6;
  /* #0: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #1: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1+@3) */
  w1 += w3;
  /* #5: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #6: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #7: @1 = (@1+@4) */
  w1 += w4;
  /* #8: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #9: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #10: @1 = (@1+@5) */
  w1 += w5;
  /* #11: @1 = sqrt(@1) */
  w1 = sqrt( w1 );
  /* #12: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #13: @6 = zeros(11x1,4nz) */
  casadi_clear(w6, 4);
  /* #14: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #15: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #16: @0 = (@0/@1) */
  w0 /= w1;
  /* #17: (@6[0] = @0) */
  for (rr=w6+0, ss=(&w0); rr!=w6+1; rr+=1) *rr = *ss++;
  /* #18: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #19: @2 = (@2/@1) */
  w2 /= w1;
  /* #20: (@6[1] = @2) */
  for (rr=w6+1, ss=(&w2); rr!=w6+2; rr+=1) *rr = *ss++;
  /* #21: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #22: @3 = (@3/@1) */
  w3 /= w1;
  /* #23: (@6[2] = @3) */
  for (rr=w6+2, ss=(&w3); rr!=w6+3; rr+=1) *rr = *ss++;
  /* #24: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #25: @4 = (@4/@1) */
  w4 /= w1;
  /* #26: (@6[3] = @4) */
  for (rr=w6+3, ss=(&w4); rr!=w6+4; rr+=1) *rr = *ss++;
  /* #27: output[1][0] = @6 */
  casadi_copy(w6, 4, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
