/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[8] = {0, 1, 2, 6, 9, 12, 15, 19};
static const casadi_int casadi_s1[6] = {3, 10, 13, 16, 20, 23};
static const casadi_int casadi_s2[6] = {4, 7, 14, 17, 21, 24};
static const casadi_int casadi_s3[5] = {5, 8, 11, 18, 22};
static const casadi_int casadi_s4[38] = {10, 10, 0, 0, 0, 0, 5, 11, 17, 22, 23, 24, 25, 4, 5, 6, 7, 8, 3, 5, 6, 7, 8, 9, 3, 4, 6, 7, 8, 9, 3, 4, 5, 7, 8, 0, 1, 2};
static const casadi_int casadi_s5[38] = {10, 10, 0, 1, 2, 3, 6, 9, 12, 15, 19, 23, 25, 7, 8, 9, 4, 5, 6, 3, 5, 6, 3, 4, 6, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 4, 5};
static const casadi_int casadi_s6[23] = {10, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s7[7] = {0, 3, 6, 9, 12, 13, 14};
static const casadi_int casadi_s8[22] = {10, 4, 0, 3, 7, 11, 15, 7, 8, 9, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s9[28] = {4, 10, 0, 0, 0, 0, 3, 6, 9, 12, 13, 14, 15, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s10[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[3] = {10, 0, 0};

/* Translational_drone_impl_dae_fun_jac_x_xdot_u_z:(i0[10],i1[10],i2[4],i3[],i4[])->(o0[10],o1[10x10,25nz],o2[10x10,10nz],o3[10x4,15nz],o4[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+38, *w30=w+48, *w31=w+73, *w34=w+80, *w35=w+88, *w38=w+96, *w39=w+102, *w41=w+108, *w42=w+113, *w43=w+118, *w44=w+143, *w45=w+158, *w46=w+160, *w48=w+167, *w49=w+171, *w50=w+175;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w8 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w9 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w10;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #11: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #12: @1 = input[0][8] */
  w1 = arg[0] ? arg[0][8] : 0;
  /* #13: @2 = input[0][9] */
  w2 = arg[0] ? arg[0][9] : 0;
  /* #14: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #15: @4 = input[2][1] */
  w4 = arg[2] ? arg[2][1] : 0;
  /* #16: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #17: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #18: @6 = (-@6) */
  w6 = (- w6 );
  /* #19: @7 = input[2][2] */
  w7 = arg[2] ? arg[2][2] : 0;
  /* #20: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #21: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #22: @6 = (@6-@9) */
  w6 -= w9;
  /* #23: @9 = input[2][3] */
  w9 = arg[2] ? arg[2][3] : 0;
  /* #24: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #25: @12 = (@9*@11) */
  w12  = (w9*w11);
  /* #26: @6 = (@6-@12) */
  w6 -= w12;
  /* #27: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #28: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #29: @13 = input[0][3] */
  w13 = arg[0] ? arg[0][3] : 0;
  /* #30: @14 = (@4*@13) */
  w14  = (w4*w13);
  /* #31: @15 = (@9*@8) */
  w15  = (w9*w8);
  /* #32: @14 = (@14+@15) */
  w14 += w15;
  /* #33: @15 = (@7*@11) */
  w15  = (w7*w11);
  /* #34: @14 = (@14-@15) */
  w14 -= w15;
  /* #35: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #36: @15 = 0.5 */
  w15 = 5.0000000000000000e-01;
  /* #37: @16 = (@7*@13) */
  w16  = (w7*w13);
  /* #38: @17 = (@9*@5) */
  w17  = (w9*w5);
  /* #39: @16 = (@16-@17) */
  w16 -= w17;
  /* #40: @17 = (@4*@11) */
  w17  = (w4*w11);
  /* #41: @16 = (@16+@17) */
  w16 += w17;
  /* #42: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #43: @17 = 0.5 */
  w17 = 5.0000000000000000e-01;
  /* #44: @18 = (@9*@13) */
  w18  = (w9*w13);
  /* #45: @19 = (@7*@5) */
  w19  = (w7*w5);
  /* #46: @18 = (@18+@19) */
  w18 += w19;
  /* #47: @19 = (@4*@8) */
  w19  = (w4*w8);
  /* #48: @18 = (@18-@19) */
  w18 -= w19;
  /* #49: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #50: @19 = (@13*@8) */
  w19  = (w13*w8);
  /* #51: @20 = (@5*@11) */
  w20  = (w5*w11);
  /* #52: @19 = (@19+@20) */
  w19 += w20;
  /* #53: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #54: @20 = input[2][0] */
  w20 = arg[2] ? arg[2][0] : 0;
  /* #55: @21 = (@19*@20) */
  w21  = (w19*w20);
  /* #56: @22 = (@8*@11) */
  w22  = (w8*w11);
  /* #57: @23 = (@13*@5) */
  w23  = (w13*w5);
  /* #58: @22 = (@22-@23) */
  w22 -= w23;
  /* #59: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #60: @23 = (@22*@20) */
  w23  = (w22*w20);
  /* #61: @24 = 1 */
  w24 = 1.;
  /* #62: @25 = (2.*@5) */
  w25 = (2.* w5 );
  /* #63: @26 = (@25*@5) */
  w26  = (w25*w5);
  /* #64: @24 = (@24-@26) */
  w24 -= w26;
  /* #65: @26 = (2.*@8) */
  w26 = (2.* w8 );
  /* #66: @27 = (@26*@8) */
  w27  = (w26*w8);
  /* #67: @24 = (@24-@27) */
  w24 -= w27;
  /* #68: @27 = (@24*@20) */
  w27  = (w24*w20);
  /* #69: @28 = 9.81 */
  w28 = 9.8100000000000005e+00;
  /* #70: @27 = (@27-@28) */
  w27 -= w28;
  /* #71: @29 = vertcat(@0, @1, @2, @6, @14, @16, @18, @21, @23, @27) */
  rr=w29;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w27;
  /* #72: @10 = (@10-@29) */
  for (i=0, rr=w10, cs=w29; i<10; ++i) (*rr++) -= (*cs++);
  /* #73: output[0][0] = @10 */
  casadi_copy(w10, 10, res[0]);
  /* #74: @30 = zeros(10x10,25nz) */
  casadi_clear(w30, 25);
  /* #75: @31 = ones(10x1,7nz) */
  casadi_fill(w31, 7, 1.);
  /* #76: {NULL, NULL, NULL, @0, NULL, NULL, NULL, @1, @2, @6} = vertsplit(@31) */
  w0 = w31[3];
  w1 = w31[4];
  w2 = w31[5];
  w6 = w31[6];
  /* #77: @32 = 00 */
  /* #78: @14 = (@4*@0) */
  w14  = (w4*w0);
  /* #79: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #80: @16 = (@7*@0) */
  w16  = (w7*w0);
  /* #81: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #82: @18 = (@9*@0) */
  w18  = (w9*w0);
  /* #83: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #84: @21 = (@8*@0) */
  w21  = (w8*w0);
  /* #85: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #86: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #87: @0 = (@5*@0) */
  w0  = (w5*w0);
  /* #88: @0 = (-@0) */
  w0 = (- w0 );
  /* #89: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #90: @0 = (@20*@0) */
  w0  = (w20*w0);
  /* #91: @33 = 00 */
  /* #92: @34 = vertcat(@1, @2, @6, @32, @14, @16, @18, @21, @0, @33) */
  rr=w34;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w0;
  /* #93: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<8; ++i) *rr++ = (- *cs++ );
  /* #94: @35 = @34[:8] */
  for (rr=w35, ss=w34+0; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #95: (@30[0, 1, 2, 6, 9, 12, 15, 19] = @35) */
  for (cii=casadi_s0, rr=w30, ss=w35; cii!=casadi_s0+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #96: @32 = 00 */
  /* #97: @33 = 00 */
  /* #98: @36 = 00 */
  /* #99: @1 = ones(10x1,1nz) */
  w1 = 1.;
  /* #100: {NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #101: @1 = (@4*@2) */
  w1  = (w4*w2);
  /* #102: @1 = (@3*@1) */
  w1  = (w3*w1);
  /* #103: @1 = (-@1) */
  w1 = (- w1 );
  /* #104: @37 = 00 */
  /* #105: @6 = (@9*@2) */
  w6  = (w9*w2);
  /* #106: @6 = (@15*@6) */
  w6  = (w15*w6);
  /* #107: @6 = (-@6) */
  w6 = (- w6 );
  /* #108: @14 = (@7*@2) */
  w14  = (w7*w2);
  /* #109: @14 = (@17*@14) */
  w14  = (w17*w14);
  /* #110: @16 = (@11*@2) */
  w16  = (w11*w2);
  /* #111: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #112: @16 = (@20*@16) */
  w16  = (w20*w16);
  /* #113: @18 = (@13*@2) */
  w18  = (w13*w2);
  /* #114: @18 = (-@18) */
  w18 = (- w18 );
  /* #115: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #116: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #117: @21 = (2.*@2) */
  w21 = (2.* w2 );
  /* #118: @21 = (@5*@21) */
  w21  = (w5*w21);
  /* #119: @25 = (@25*@2) */
  w25 *= w2;
  /* #120: @21 = (@21+@25) */
  w21 += w25;
  /* #121: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #122: @21 = (-@21) */
  w21 = (- w21 );
  /* #123: @38 = vertcat(@32, @33, @36, @1, @37, @6, @14, @16, @18, @21) */
  rr=w38;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w21;
  /* #124: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<6; ++i) *rr++ = (- *cs++ );
  /* #125: @39 = @38[:6] */
  for (rr=w39, ss=w38+0; ss!=w38+6; ss+=1) *rr++ = *ss;
  /* #126: (@30[3, 10, 13, 16, 20, 23] = @39) */
  for (cii=casadi_s1, rr=w30, ss=w39; cii!=casadi_s1+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #127: @32 = 00 */
  /* #128: @33 = 00 */
  /* #129: @36 = 00 */
  /* #130: @1 = ones(10x1,1nz) */
  w1 = 1.;
  /* #131: {NULL, NULL, NULL, NULL, NULL, @6, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w6 = w1;
  /* #132: @1 = (@7*@6) */
  w1  = (w7*w6);
  /* #133: @1 = (@3*@1) */
  w1  = (w3*w1);
  /* #134: @1 = (-@1) */
  w1 = (- w1 );
  /* #135: @14 = (@9*@6) */
  w14  = (w9*w6);
  /* #136: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #137: @37 = 00 */
  /* #138: @16 = (@4*@6) */
  w16  = (w4*w6);
  /* #139: @16 = (@17*@16) */
  w16  = (w17*w16);
  /* #140: @16 = (-@16) */
  w16 = (- w16 );
  /* #141: @18 = (@13*@6) */
  w18  = (w13*w6);
  /* #142: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #143: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #144: @21 = (@11*@6) */
  w21  = (w11*w6);
  /* #145: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #146: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #147: @25 = (2.*@6) */
  w25 = (2.* w6 );
  /* #148: @25 = (@8*@25) */
  w25  = (w8*w25);
  /* #149: @26 = (@26*@6) */
  w26 *= w6;
  /* #150: @25 = (@25+@26) */
  w25 += w26;
  /* #151: @25 = (@20*@25) */
  w25  = (w20*w25);
  /* #152: @25 = (-@25) */
  w25 = (- w25 );
  /* #153: @39 = vertcat(@32, @33, @36, @1, @14, @37, @16, @18, @21, @25) */
  rr=w39;
  *rr++ = w1;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w25;
  /* #154: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<6; ++i) *rr++ = (- *cs++ );
  /* #155: @38 = @39[:6] */
  for (rr=w38, ss=w39+0; ss!=w39+6; ss+=1) *rr++ = *ss;
  /* #156: (@30[4, 7, 14, 17, 21, 24] = @38) */
  for (cii=casadi_s2, rr=w30, ss=w38; cii!=casadi_s2+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #157: @32 = 00 */
  /* #158: @33 = 00 */
  /* #159: @36 = 00 */
  /* #160: @1 = ones(10x1,1nz) */
  w1 = 1.;
  /* #161: {NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL} = vertsplit(@1) */
  w14 = w1;
  /* #162: @9 = (@9*@14) */
  w9 *= w14;
  /* #163: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #164: @9 = (-@9) */
  w9 = (- w9 );
  /* #165: @7 = (@7*@14) */
  w7 *= w14;
  /* #166: @7 = (@12*@7) */
  w7  = (w12*w7);
  /* #167: @7 = (-@7) */
  w7 = (- w7 );
  /* #168: @4 = (@4*@14) */
  w4 *= w14;
  /* #169: @4 = (@15*@4) */
  w4  = (w15*w4);
  /* #170: @37 = 00 */
  /* #171: @1 = (@5*@14) */
  w1  = (w5*w14);
  /* #172: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #173: @1 = (@20*@1) */
  w1  = (w20*w1);
  /* #174: @14 = (@8*@14) */
  w14  = (w8*w14);
  /* #175: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #176: @20 = (@20*@14) */
  w20 *= w14;
  /* #177: @40 = 00 */
  /* #178: @41 = vertcat(@32, @33, @36, @9, @7, @4, @37, @1, @20, @40) */
  rr=w41;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w20;
  /* #179: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<5; ++i) *rr++ = (- *cs++ );
  /* #180: @42 = @41[:5] */
  for (rr=w42, ss=w41+0; ss!=w41+5; ss+=1) *rr++ = *ss;
  /* #181: (@30[5, 8, 11, 18, 22] = @42) */
  for (cii=casadi_s3, rr=w30, ss=w42; cii!=casadi_s3+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #182: @43 = @30' */
  casadi_trans(w30,casadi_s5, w43, casadi_s4, iw);
  /* #183: output[1][0] = @43 */
  casadi_copy(w43, 25, res[1]);
  /* #184: @10 = zeros(10x10,10nz) */
  casadi_clear(w10, 10);
  /* #185: @29 = ones(10x1) */
  casadi_fill(w29, 10, 1.);
  /* #186: (@10[:10] = @29) */
  for (rr=w10+0, ss=w29; rr!=w10+10; rr+=1) *rr = *ss++;
  /* #187: @29 = @10' */
  casadi_trans(w10,casadi_s6, w29, casadi_s6, iw);
  /* #188: output[2][0] = @29 */
  casadi_copy(w29, 10, res[2]);
  /* #189: @44 = zeros(4x10,15nz) */
  casadi_clear(w44, 15);
  /* #190: @32 = 00 */
  /* #191: @33 = 00 */
  /* #192: @36 = 00 */
  /* #193: @45 = ones(4x1,2nz) */
  casadi_fill(w45, 2, 1.);
  /* #194: {@9, @7, NULL, NULL} = vertsplit(@45) */
  w9 = w45[0];
  w7 = w45[1];
  /* #195: @4 = (@5*@7) */
  w4  = (w5*w7);
  /* #196: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #197: @4 = (-@4) */
  w4 = (- w4 );
  /* #198: @1 = (@13*@7) */
  w1  = (w13*w7);
  /* #199: @1 = (@12*@1) */
  w1  = (w12*w1);
  /* #200: @20 = (@11*@7) */
  w20  = (w11*w7);
  /* #201: @20 = (@15*@20) */
  w20  = (w15*w20);
  /* #202: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #203: @7 = (@17*@7) */
  w7  = (w17*w7);
  /* #204: @7 = (-@7) */
  w7 = (- w7 );
  /* #205: @19 = (@19*@9) */
  w19 *= w9;
  /* #206: @22 = (@22*@9) */
  w22 *= w9;
  /* #207: @24 = (@24*@9) */
  w24 *= w9;
  /* #208: @31 = vertcat(@32, @33, @36, @4, @1, @20, @7, @19, @22, @24) */
  rr=w31;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w20;
  *rr++ = w7;
  *rr++ = w19;
  *rr++ = w22;
  *rr++ = w24;
  /* #209: @31 = (-@31) */
  for (i=0, rr=w31, cs=w31; i<7; ++i) *rr++ = (- *cs++ );
  /* #210: @46 = @31[:7] */
  for (rr=w46, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #211: (@44[0, 3, 6, 9, 12, 13, 14] = @46) */
  for (cii=casadi_s7, rr=w44, ss=w46; cii!=casadi_s7+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #212: @32 = 00 */
  /* #213: @33 = 00 */
  /* #214: @36 = 00 */
  /* #215: @4 = ones(4x1,1nz) */
  w4 = 1.;
  /* #216: {NULL, NULL, @1, NULL} = vertsplit(@4) */
  w1 = w4;
  /* #217: @4 = (@8*@1) */
  w4  = (w8*w1);
  /* #218: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #219: @4 = (-@4) */
  w4 = (- w4 );
  /* #220: @20 = (@11*@1) */
  w20  = (w11*w1);
  /* #221: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #222: @20 = (-@20) */
  w20 = (- w20 );
  /* #223: @7 = (@13*@1) */
  w7  = (w13*w1);
  /* #224: @7 = (@15*@7) */
  w7  = (w15*w7);
  /* #225: @1 = (@5*@1) */
  w1  = (w5*w1);
  /* #226: @1 = (@17*@1) */
  w1  = (w17*w1);
  /* #227: @37 = 00 */
  /* #228: @40 = 00 */
  /* #229: @47 = 00 */
  /* #230: @48 = vertcat(@32, @33, @36, @4, @20, @7, @1, @37, @40, @47) */
  rr=w48;
  *rr++ = w4;
  *rr++ = w20;
  *rr++ = w7;
  *rr++ = w1;
  /* #231: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) *rr++ = (- *cs++ );
  /* #232: @49 = @48[:4] */
  for (rr=w49, ss=w48+0; ss!=w48+4; ss+=1) *rr++ = *ss;
  /* #233: (@44[1:13:3] = @49) */
  for (rr=w44+1, ss=w49; rr!=w44+13; rr+=3) *rr = *ss++;
  /* #234: @32 = 00 */
  /* #235: @33 = 00 */
  /* #236: @36 = 00 */
  /* #237: @4 = ones(4x1,1nz) */
  w4 = 1.;
  /* #238: {NULL, NULL, NULL, @20} = vertsplit(@4) */
  w20 = w4;
  /* #239: @11 = (@11*@20) */
  w11 *= w20;
  /* #240: @3 = (@3*@11) */
  w3 *= w11;
  /* #241: @3 = (-@3) */
  w3 = (- w3 );
  /* #242: @8 = (@8*@20) */
  w8 *= w20;
  /* #243: @12 = (@12*@8) */
  w12 *= w8;
  /* #244: @5 = (@5*@20) */
  w5 *= w20;
  /* #245: @15 = (@15*@5) */
  w15 *= w5;
  /* #246: @15 = (-@15) */
  w15 = (- w15 );
  /* #247: @13 = (@13*@20) */
  w13 *= w20;
  /* #248: @17 = (@17*@13) */
  w17 *= w13;
  /* #249: @37 = 00 */
  /* #250: @40 = 00 */
  /* #251: @47 = 00 */
  /* #252: @49 = vertcat(@32, @33, @36, @3, @12, @15, @17, @37, @40, @47) */
  rr=w49;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w17;
  /* #253: @49 = (-@49) */
  for (i=0, rr=w49, cs=w49; i<4; ++i) *rr++ = (- *cs++ );
  /* #254: @48 = @49[:4] */
  for (rr=w48, ss=w49+0; ss!=w49+4; ss+=1) *rr++ = *ss;
  /* #255: (@44[2:14:3] = @48) */
  for (rr=w44+2, ss=w48; rr!=w44+14; rr+=3) *rr = *ss++;
  /* #256: @50 = @44' */
  casadi_trans(w44,casadi_s9, w50, casadi_s8, iw);
  /* #257: output[3][0] = @50 */
  casadi_copy(w50, 15, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s4;
    case 2: return casadi_s6;
    case 3: return casadi_s8;
    case 4: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 190;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
