/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {11, 1, 0, 8, 3, 4, 5, 6, 7, 8, 9, 10};

/* Translational_drone_expl_vde_adj:(i0[6],i1[6],i2[5],i3[])->(o0[11x1,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  w4 = w0[3];
  w5 = w0[4];
  w6 = w0[5];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #5: @3 = 1 */
  w3 = 1.;
  /* #6: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #7: @1 = (2.*@2) */
  w1 = (2.* w2 );
  /* #8: @7 = (@1*@2) */
  w7  = (w1*w2);
  /* #9: @3 = (@3-@7) */
  w3 -= w7;
  /* #10: @7 = input[2][3] */
  w7 = arg[2] ? arg[2][3] : 0;
  /* #11: @8 = (2.*@7) */
  w8 = (2.* w7 );
  /* #12: @9 = (@8*@7) */
  w9  = (w8*w7);
  /* #13: @3 = (@3-@9) */
  w3 -= w9;
  /* #14: @3 = (@3*@6) */
  w3 *= w6;
  /* #15: @9 = input[2][4] */
  w9 = arg[2] ? arg[2][4] : 0;
  /* #16: @10 = (@7*@9) */
  w10  = (w7*w9);
  /* #17: @11 = input[2][1] */
  w11 = arg[2] ? arg[2][1] : 0;
  /* #18: @12 = (@11*@2) */
  w12  = (w11*w2);
  /* #19: @10 = (@10-@12) */
  w10 -= w12;
  /* #20: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #21: @10 = (@10*@5) */
  w10 *= w5;
  /* #22: @3 = (@3+@10) */
  w3 += w10;
  /* #23: @10 = (@11*@7) */
  w10  = (w11*w7);
  /* #24: @12 = (@2*@9) */
  w12  = (w2*w9);
  /* #25: @10 = (@10+@12) */
  w10 += w12;
  /* #26: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #27: @10 = (@10*@4) */
  w10 *= w4;
  /* #28: @3 = (@3+@10) */
  w3 += w10;
  /* #29: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #30: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #31: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #32: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #33: @10 = (@7*@4) */
  w10  = (w7*w4);
  /* #34: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #35: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #36: @12 = (@2*@5) */
  w12  = (w2*w5);
  /* #37: @10 = (@10-@12) */
  w10 -= w12;
  /* #38: output[0][4] = @10 */
  if (res[0]) res[0][4] = w10;
  /* #39: @3 = (@3*@6) */
  w3 *= w6;
  /* #40: @6 = (@2*@3) */
  w6  = (w2*w3);
  /* #41: @6 = (-@6) */
  w6 = (- w6 );
  /* #42: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #43: @1 = (@1*@3) */
  w1 *= w3;
  /* #44: @6 = (@6-@1) */
  w6 -= w1;
  /* #45: @1 = (@11*@5) */
  w1  = (w11*w5);
  /* #46: @6 = (@6-@1) */
  w6 -= w1;
  /* #47: @1 = (@9*@4) */
  w1  = (w9*w4);
  /* #48: @6 = (@6+@1) */
  w6 += w1;
  /* #49: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  /* #50: @6 = (@7*@3) */
  w6  = (w7*w3);
  /* #51: @6 = (-@6) */
  w6 = (- w6 );
  /* #52: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #53: @8 = (@8*@3) */
  w8 *= w3;
  /* #54: @6 = (@6-@8) */
  w6 -= w8;
  /* #55: @9 = (@9*@5) */
  w9 *= w5;
  /* #56: @6 = (@6+@9) */
  w6 += w9;
  /* #57: @11 = (@11*@4) */
  w11 *= w4;
  /* #58: @6 = (@6+@11) */
  w6 += w11;
  /* #59: output[0][6] = @6 */
  if (res[0]) res[0][6] = w6;
  /* #60: @7 = (@7*@5) */
  w7 *= w5;
  /* #61: @2 = (@2*@4) */
  w2 *= w4;
  /* #62: @7 = (@7+@2) */
  w7 += w2;
  /* #63: output[0][7] = @7 */
  if (res[0]) res[0][7] = w7;
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 18;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
