/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {14, 1, 0, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* Translational_drone_expl_vde_adj:(i0[10],i1[10],i2[4],i3[])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 10, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  /* #4: @13 = (@1*@10) */
  w13  = (w1*w10);
  /* #5: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #6: @14 = (@0*@13) */
  w14  = (w0*w13);
  /* #7: @15 = input[0][4] */
  w15 = arg[0] ? arg[0][4] : 0;
  /* #8: @16 = (@1*@11) */
  w16  = (w1*w11);
  /* #9: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #10: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #11: @14 = (@14-@17) */
  w14 -= w17;
  /* #12: @17 = input[2][3] */
  w17 = arg[2] ? arg[2][3] : 0;
  /* #13: @18 = 0.5 */
  w18 = 5.0000000000000000e-01;
  /* #14: @18 = (@18*@9) */
  w18 *= w9;
  /* #15: @9 = (@17*@18) */
  w9  = (w17*w18);
  /* #16: @14 = (@14+@9) */
  w14 += w9;
  /* #17: @9 = input[2][2] */
  w9 = arg[2] ? arg[2][2] : 0;
  /* #18: @19 = 0.5 */
  w19 = 5.0000000000000000e-01;
  /* #19: @19 = (@19*@8) */
  w19 *= w8;
  /* #20: @8 = (@9*@19) */
  w8  = (w9*w19);
  /* #21: @14 = (@14+@8) */
  w14 += w8;
  /* #22: @8 = input[2][1] */
  w8 = arg[2] ? arg[2][1] : 0;
  /* #23: @20 = 0.5 */
  w20 = 5.0000000000000000e-01;
  /* #24: @20 = (@20*@7) */
  w20 *= w7;
  /* #25: @7 = (@8*@20) */
  w7  = (w8*w20);
  /* #26: @14 = (@14+@7) */
  w14 += w7;
  /* #27: output[0][0] = @14 */
  if (res[0]) res[0][0] = w14;
  /* #28: @1 = (@1*@12) */
  w1 *= w12;
  /* #29: @14 = (@15*@1) */
  w14  = (w15*w1);
  /* #30: @14 = (-@14) */
  w14 = (- w14 );
  /* #31: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #32: @7 = (2.*@15) */
  w7 = (2.* w15 );
  /* #33: @21 = (@7*@1) */
  w21  = (w7*w1);
  /* #34: @14 = (@14-@21) */
  w14 -= w21;
  /* #35: @21 = input[0][3] */
  w21 = arg[0] ? arg[0][3] : 0;
  /* #36: @22 = (@21*@16) */
  w22  = (w21*w16);
  /* #37: @14 = (@14-@22) */
  w14 -= w22;
  /* #38: @22 = input[0][6] */
  w22 = arg[0] ? arg[0][6] : 0;
  /* #39: @23 = (@22*@13) */
  w23  = (w22*w13);
  /* #40: @14 = (@14+@23) */
  w14 += w23;
  /* #41: @23 = (@9*@18) */
  w23  = (w9*w18);
  /* #42: @14 = (@14+@23) */
  w14 += w23;
  /* #43: @23 = (@17*@19) */
  w23  = (w17*w19);
  /* #44: @14 = (@14-@23) */
  w14 -= w23;
  /* #45: @23 = 0.5 */
  w23 = 5.0000000000000000e-01;
  /* #46: @23 = (@23*@6) */
  w23 *= w6;
  /* #47: @6 = (@8*@23) */
  w6  = (w8*w23);
  /* #48: @14 = (@14-@6) */
  w14 -= w6;
  /* #49: output[0][1] = @14 */
  if (res[0]) res[0][1] = w14;
  /* #50: @14 = (@0*@1) */
  w14  = (w0*w1);
  /* #51: @14 = (-@14) */
  w14 = (- w14 );
  /* #52: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #53: @6 = (2.*@0) */
  w6 = (2.* w0 );
  /* #54: @1 = (@6*@1) */
  w1  = (w6*w1);
  /* #55: @14 = (@14-@1) */
  w14 -= w1;
  /* #56: @1 = (@22*@16) */
  w1  = (w22*w16);
  /* #57: @14 = (@14+@1) */
  w14 += w1;
  /* #58: @1 = (@21*@13) */
  w1  = (w21*w13);
  /* #59: @14 = (@14+@1) */
  w14 += w1;
  /* #60: @1 = (@8*@18) */
  w1  = (w8*w18);
  /* #61: @14 = (@14-@1) */
  w14 -= w1;
  /* #62: @1 = (@17*@20) */
  w1  = (w17*w20);
  /* #63: @14 = (@14+@1) */
  w14 += w1;
  /* #64: @1 = (@9*@23) */
  w1  = (w9*w23);
  /* #65: @14 = (@14-@1) */
  w14 -= w1;
  /* #66: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #67: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #68: @13 = (@15*@13) */
  w13  = (w15*w13);
  /* #69: @16 = (@16+@13) */
  w16 += w13;
  /* #70: @8 = (@8*@19) */
  w8 *= w19;
  /* #71: @16 = (@16+@8) */
  w16 += w8;
  /* #72: @9 = (@9*@20) */
  w9 *= w20;
  /* #73: @16 = (@16-@9) */
  w16 -= w9;
  /* #74: @17 = (@17*@23) */
  w17 *= w23;
  /* #75: @16 = (@16-@17) */
  w16 -= w17;
  /* #76: output[0][3] = @16 */
  if (res[0]) res[0][3] = w16;
  /* #77: output[0][4] = @3 */
  if (res[0]) res[0][4] = w3;
  /* #78: output[0][5] = @4 */
  if (res[0]) res[0][5] = w4;
  /* #79: output[0][6] = @5 */
  if (res[0]) res[0][6] = w5;
  /* #80: @5 = 1 */
  w5 = 1.;
  /* #81: @7 = (@7*@15) */
  w7 *= w15;
  /* #82: @5 = (@5-@7) */
  w5 -= w7;
  /* #83: @6 = (@6*@0) */
  w6 *= w0;
  /* #84: @5 = (@5-@6) */
  w5 -= w6;
  /* #85: @5 = (@5*@12) */
  w5 *= w12;
  /* #86: @12 = (@0*@22) */
  w12  = (w0*w22);
  /* #87: @6 = (@21*@15) */
  w6  = (w21*w15);
  /* #88: @12 = (@12-@6) */
  w12 -= w6;
  /* #89: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #90: @12 = (@12*@11) */
  w12 *= w11;
  /* #91: @5 = (@5+@12) */
  w5 += w12;
  /* #92: @12 = (@21*@0) */
  w12  = (w21*w0);
  /* #93: @11 = (@15*@22) */
  w11  = (w15*w22);
  /* #94: @12 = (@12+@11) */
  w12 += w11;
  /* #95: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #96: @12 = (@12*@10) */
  w12 *= w10;
  /* #97: @5 = (@5+@12) */
  w5 += w12;
  /* #98: output[0][7] = @5 */
  if (res[0]) res[0][7] = w5;
  /* #99: @5 = (@22*@19) */
  w5  = (w22*w19);
  /* #100: @12 = (@0*@18) */
  w12  = (w0*w18);
  /* #101: @5 = (@5-@12) */
  w5 -= w12;
  /* #102: @12 = (@21*@20) */
  w12  = (w21*w20);
  /* #103: @5 = (@5+@12) */
  w5 += w12;
  /* #104: @12 = (@15*@23) */
  w12  = (w15*w23);
  /* #105: @5 = (@5-@12) */
  w5 -= w12;
  /* #106: output[0][8] = @5 */
  if (res[0]) res[0][8] = w5;
  /* #107: @5 = (@15*@18) */
  w5  = (w15*w18);
  /* #108: @12 = (@21*@19) */
  w12  = (w21*w19);
  /* #109: @5 = (@5+@12) */
  w5 += w12;
  /* #110: @12 = (@22*@20) */
  w12  = (w22*w20);
  /* #111: @5 = (@5-@12) */
  w5 -= w12;
  /* #112: @12 = (@0*@23) */
  w12  = (w0*w23);
  /* #113: @5 = (@5-@12) */
  w5 -= w12;
  /* #114: output[0][9] = @5 */
  if (res[0]) res[0][9] = w5;
  /* #115: @21 = (@21*@18) */
  w21 *= w18;
  /* #116: @15 = (@15*@19) */
  w15 *= w19;
  /* #117: @21 = (@21-@15) */
  w21 -= w15;
  /* #118: @0 = (@0*@20) */
  w0 *= w20;
  /* #119: @21 = (@21+@0) */
  w21 += w0;
  /* #120: @22 = (@22*@23) */
  w22 *= w23;
  /* #121: @21 = (@21-@22) */
  w21 -= w22;
  /* #122: output[0][10] = @21 */
  if (res[0]) res[0][10] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
