/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Planar_drone_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[14] = {6, 6, 0, 0, 0, 2, 3, 4, 5, 3, 4, 0, 1, 2};
static const casadi_int casadi_s1[14] = {6, 6, 0, 1, 2, 3, 4, 5, 5, 3, 4, 5, 2, 2};
static const casadi_int casadi_s2[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[3] = {6, 0, 0};

/* Planar_drone_impl_dae_fun_jac_x_xdot_z:(i0[6],i1[6],i2[2],i3[],i4[])->(o0[6],o1[6x6,5nz],o2[6x6,6nz],o3[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+6, w7, w8, w9, w10, *w11=w+16, *w12=w+22, *w14=w+27, *w15=w+32;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #8: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #9: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #10: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #11: @4 = 0.027 */
  w4 = 2.7000000000000000e-02;
  /* #12: @4 = (@3/@4) */
  w4  = (w3/w4);
  /* #13: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #14: @7 = sin(@5) */
  w7 = sin( w5 );
  /* #15: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #16: @7 = (-@7) */
  w7 = (- w7 );
  /* #17: @8 = -9.81 */
  w8 = -9.8100000000000005e+00;
  /* #18: @9 = 0.027 */
  w9 = 2.7000000000000000e-02;
  /* #19: @3 = (@3/@9) */
  w3 /= w9;
  /* #20: @9 = cos(@5) */
  w9 = cos( w5 );
  /* #21: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #22: @8 = (@8+@9) */
  w8 += w9;
  /* #23: @9 = input[2][1] */
  w9 = arg[2] ? arg[2][1] : 0;
  /* #24: @10 = 1.65717e-05 */
  w10 = 1.6571710000000000e-05;
  /* #25: @9 = (@9/@10) */
  w9 /= w10;
  /* #26: @11 = vertcat(@0, @1, @2, @7, @8, @9) */
  rr=w11;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #27: @6 = (@6-@11) */
  for (i=0, rr=w6, cs=w11; i<6; ++i) (*rr++) -= (*cs++);
  /* #28: output[0][0] = @6 */
  casadi_copy(w6, 6, res[0]);
  /* #29: @12 = zeros(6x6,5nz) */
  casadi_clear(w12, 5);
  /* #30: @6 = ones(6x1) */
  casadi_fill(w6, 6, 1.);
  /* #31: {NULL, NULL, @0, @1, @2, @7} = vertsplit(@6) */
  w0 = w6[2];
  w1 = w6[3];
  w2 = w6[4];
  w7 = w6[5];
  /* #32: @8 = cos(@5) */
  w8 = cos( w5 );
  /* #33: @8 = (@8*@0) */
  w8 *= w0;
  /* #34: @4 = (@4*@8) */
  w4 *= w8;
  /* #35: @4 = (-@4) */
  w4 = (- w4 );
  /* #36: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #37: @5 = (@5*@0) */
  w5 *= w0;
  /* #38: @3 = (@3*@5) */
  w3 *= w5;
  /* #39: @3 = (-@3) */
  w3 = (- w3 );
  /* #40: @13 = 00 */
  /* #41: @14 = vertcat(@1, @2, @7, @4, @3, @13) */
  rr=w14;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w3;
  /* #42: @14 = (-@14) */
  for (i=0, rr=w14, cs=w14; i<5; ++i) *rr++ = (- *cs++ );
  /* #43: @15 = @14[:5] */
  for (rr=w15, ss=w14+0; ss!=w14+5; ss+=1) *rr++ = *ss;
  /* #44: (@12[:5] = @15) */
  for (rr=w12+0, ss=w15; rr!=w12+5; rr+=1) *rr = *ss++;
  /* #45: @15 = @12' */
  casadi_trans(w12,casadi_s1, w15, casadi_s0, iw);
  /* #46: output[1][0] = @15 */
  casadi_copy(w15, 5, res[1]);
  /* #47: @6 = zeros(6x6,6nz) */
  casadi_clear(w6, 6);
  /* #48: @11 = ones(6x1) */
  casadi_fill(w11, 6, 1.);
  /* #49: (@6[:6] = @11) */
  for (rr=w6+0, ss=w11; rr!=w6+6; rr+=1) *rr = *ss++;
  /* #50: @11 = @6' */
  casadi_trans(w6,casadi_s2, w11, casadi_s2, iw);
  /* #51: output[2][0] = @11 */
  casadi_copy(w11, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Planar_drone_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Planar_drone_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Planar_drone_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Planar_drone_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Planar_drone_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Planar_drone_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Planar_drone_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Planar_drone_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Planar_drone_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Planar_drone_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real Planar_drone_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Planar_drone_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Planar_drone_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Planar_drone_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Planar_drone_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Planar_drone_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 37;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
