/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[3] = {2, 7, 11};
static const casadi_int casadi_s1[3] = {3, 8, 12};
static const casadi_int casadi_s2[21] = {6, 5, 0, 3, 5, 8, 11, 13, 3, 4, 5, 3, 4, 3, 4, 5, 3, 4, 5, 3, 4};
static const casadi_int casadi_s3[22] = {5, 6, 0, 0, 0, 0, 5, 10, 13, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 2, 3};
static const casadi_int casadi_s4[36] = {6, 5, 0, 6, 11, 17, 23, 28, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[23] = {6, 5, 0, 3, 6, 9, 12, 15, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[38] = {6, 5, 0, 6, 12, 18, 24, 30, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[27] = {6, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* Translational_drone_expl_vde_forw:(i0[6],i1[6x6],i2[6x5],i3[5],i4[])->(o0[6],o1[6x6,18nz],o2[6x5,28nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+18, *w13=w+54, *w14=w+60, *w15=w+66, *w16=w+72, *w17=w+78, *w18=w+84, w19, *w20=w+91, *w24=w+104, *w25=w+107, *w27=w+110, *w28=w+112, *w29=w+114, *w30=w+127, *w31=w+155, *w32=w+185, *w33=w+188, *w34=w+191, *w35=w+194, *w36=w+209;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[3][1] */
  w0 = arg[3] ? arg[3][1] : 0;
  /* #7: @1 = input[3][3] */
  w1 = arg[3] ? arg[3][3] : 0;
  /* #8: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #9: @3 = input[3][2] */
  w3 = arg[3] ? arg[3][2] : 0;
  /* #10: @4 = input[3][4] */
  w4 = arg[3] ? arg[3][4] : 0;
  /* #11: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #12: @2 = (@2+@5) */
  w2 += w5;
  /* #13: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #14: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #15: @6 = (@2*@5) */
  w6  = (w2*w5);
  /* #16: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #17: @6 = (@1*@4) */
  w6  = (w1*w4);
  /* #18: @7 = (@0*@3) */
  w7  = (w0*w3);
  /* #19: @6 = (@6-@7) */
  w6 -= w7;
  /* #20: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #21: @7 = (@6*@5) */
  w7  = (w6*w5);
  /* #22: output[0][4] = @7 */
  if (res[0]) res[0][4] = w7;
  /* #23: @7 = 1 */
  w7 = 1.;
  /* #24: @8 = (2.*@3) */
  w8 = (2.* w3 );
  /* #25: @9 = (@8*@3) */
  w9  = (w8*w3);
  /* #26: @7 = (@7-@9) */
  w7 -= w9;
  /* #27: @9 = (2.*@1) */
  w9 = (2.* w1 );
  /* #28: @10 = (@9*@1) */
  w10  = (w9*w1);
  /* #29: @7 = (@7-@10) */
  w7 -= w10;
  /* #30: @10 = (@7*@5) */
  w10  = (w7*w5);
  /* #31: @11 = 9.81 */
  w11 = 9.8100000000000005e+00;
  /* #32: @10 = (@10-@11) */
  w10 -= w11;
  /* #33: output[0][5] = @10 */
  if (res[0]) res[0][5] = w10;
  /* #34: @12 = input[1][0] */
  casadi_copy(arg[1], 36, w12);
  /* #35: {@13, @14, @15, @16, @17, @18} = horzsplit(@12) */
  casadi_copy(w12, 6, w13);
  casadi_copy(w12+6, 6, w14);
  casadi_copy(w12+12, 6, w15);
  casadi_copy(w12+18, 6, w16);
  casadi_copy(w12+24, 6, w17);
  casadi_copy(w12+30, 6, w18);
  /* #36: {NULL, NULL, NULL, @10, @11, @19} = vertsplit(@13) */
  w10 = w13[3];
  w11 = w13[4];
  w19 = w13[5];
  /* #37: output[1][0] = @10 */
  if (res[1]) res[1][0] = w10;
  /* #38: output[1][1] = @11 */
  if (res[1]) res[1][1] = w11;
  /* #39: output[1][2] = @19 */
  if (res[1]) res[1][2] = w19;
  /* #40: {NULL, NULL, NULL, @19, @11, @10} = vertsplit(@14) */
  w19 = w14[3];
  w11 = w14[4];
  w10 = w14[5];
  /* #41: output[1][3] = @19 */
  if (res[1]) res[1][3] = w19;
  /* #42: output[1][4] = @11 */
  if (res[1]) res[1][4] = w11;
  /* #43: output[1][5] = @10 */
  if (res[1]) res[1][5] = w10;
  /* #44: {NULL, NULL, NULL, @10, @11, @19} = vertsplit(@15) */
  w10 = w15[3];
  w11 = w15[4];
  w19 = w15[5];
  /* #45: output[1][6] = @10 */
  if (res[1]) res[1][6] = w10;
  /* #46: output[1][7] = @11 */
  if (res[1]) res[1][7] = w11;
  /* #47: output[1][8] = @19 */
  if (res[1]) res[1][8] = w19;
  /* #48: {NULL, NULL, NULL, @19, @11, @10} = vertsplit(@16) */
  w19 = w16[3];
  w11 = w16[4];
  w10 = w16[5];
  /* #49: output[1][9] = @19 */
  if (res[1]) res[1][9] = w19;
  /* #50: output[1][10] = @11 */
  if (res[1]) res[1][10] = w11;
  /* #51: output[1][11] = @10 */
  if (res[1]) res[1][11] = w10;
  /* #52: {NULL, NULL, NULL, @10, @11, @19} = vertsplit(@17) */
  w10 = w17[3];
  w11 = w17[4];
  w19 = w17[5];
  /* #53: output[1][12] = @10 */
  if (res[1]) res[1][12] = w10;
  /* #54: output[1][13] = @11 */
  if (res[1]) res[1][13] = w11;
  /* #55: output[1][14] = @19 */
  if (res[1]) res[1][14] = w19;
  /* #56: {NULL, NULL, NULL, @19, @11, @10} = vertsplit(@18) */
  w19 = w18[3];
  w11 = w18[4];
  w10 = w18[5];
  /* #57: output[1][15] = @19 */
  if (res[1]) res[1][15] = w19;
  /* #58: output[1][16] = @11 */
  if (res[1]) res[1][16] = w11;
  /* #59: output[1][17] = @10 */
  if (res[1]) res[1][17] = w10;
  /* #60: @20 = zeros(5x6,13nz) */
  casadi_clear(w20, 13);
  /* #61: @21 = 00 */
  /* #62: @22 = 00 */
  /* #63: @23 = 00 */
  /* #64: @10 = ones(5x1,1nz) */
  w10 = 1.;
  /* #65: {@11, NULL, NULL, NULL, NULL} = vertsplit(@10) */
  w11 = w10;
  /* #66: @2 = (@2*@11) */
  w2 *= w11;
  /* #67: @6 = (@6*@11) */
  w6 *= w11;
  /* #68: @7 = (@7*@11) */
  w7 *= w11;
  /* #69: @24 = vertcat(@21, @22, @23, @2, @6, @7) */
  rr=w24;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w7;
  /* #70: @25 = @24[:3] */
  for (rr=w25, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #71: (@20[:15:5] = @25) */
  for (rr=w20+0, ss=w25; rr!=w20+15; rr+=5) *rr = *ss++;
  /* #72: @21 = 00 */
  /* #73: @22 = 00 */
  /* #74: @23 = 00 */
  /* #75: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #76: {NULL, @6, NULL, NULL, NULL} = vertsplit(@2) */
  w6 = w2;
  /* #77: @2 = (@1*@6) */
  w2  = (w1*w6);
  /* #78: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #79: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #80: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #81: @6 = (-@6) */
  w6 = (- w6 );
  /* #82: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #83: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #84: @26 = 00 */
  /* #85: @27 = vertcat(@21, @22, @23, @2, @6, @26) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w6;
  /* #86: @28 = @27[:2] */
  for (rr=w28, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #87: (@20[1:11:5] = @28) */
  for (rr=w20+1, ss=w28; rr!=w20+11; rr+=5) *rr = *ss++;
  /* #88: @21 = 00 */
  /* #89: @22 = 00 */
  /* #90: @23 = 00 */
  /* #91: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #92: {NULL, NULL, @6, NULL, NULL} = vertsplit(@2) */
  w6 = w2;
  /* #93: @2 = (@4*@6) */
  w2  = (w4*w6);
  /* #94: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #95: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #96: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #97: @7 = (-@7) */
  w7 = (- w7 );
  /* #98: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #99: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #100: @11 = (2.*@6) */
  w11 = (2.* w6 );
  /* #101: @11 = (@3*@11) */
  w11  = (w3*w11);
  /* #102: @8 = (@8*@6) */
  w8 *= w6;
  /* #103: @11 = (@11+@8) */
  w11 += w8;
  /* #104: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #105: @11 = (-@11) */
  w11 = (- w11 );
  /* #106: @25 = vertcat(@21, @22, @23, @2, @7, @11) */
  rr=w25;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w11;
  /* #107: @24 = @25[:3] */
  for (rr=w24, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #108: (@20[2, 7, 11] = @24) */
  for (cii=casadi_s0, rr=w20, ss=w24; cii!=casadi_s0+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #109: @21 = 00 */
  /* #110: @22 = 00 */
  /* #111: @23 = 00 */
  /* #112: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #113: {NULL, NULL, NULL, @7, NULL} = vertsplit(@2) */
  w7 = w2;
  /* #114: @0 = (@0*@7) */
  w0 *= w7;
  /* #115: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #116: @0 = (@5*@0) */
  w0  = (w5*w0);
  /* #117: @4 = (@4*@7) */
  w4 *= w7;
  /* #118: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #119: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #120: @2 = (2.*@7) */
  w2 = (2.* w7 );
  /* #121: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #122: @9 = (@9*@7) */
  w9 *= w7;
  /* #123: @2 = (@2+@9) */
  w2 += w9;
  /* #124: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #125: @2 = (-@2) */
  w2 = (- w2 );
  /* #126: @24 = vertcat(@21, @22, @23, @0, @4, @2) */
  rr=w24;
  *rr++ = w0;
  *rr++ = w4;
  *rr++ = w2;
  /* #127: @25 = @24[:3] */
  for (rr=w25, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #128: (@20[3, 8, 12] = @25) */
  for (cii=casadi_s1, rr=w20, ss=w25; cii!=casadi_s1+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #129: @21 = 00 */
  /* #130: @22 = 00 */
  /* #131: @23 = 00 */
  /* #132: @0 = ones(5x1,1nz) */
  w0 = 1.;
  /* #133: {NULL, NULL, NULL, NULL, @4} = vertsplit(@0) */
  w4 = w0;
  /* #134: @3 = (@3*@4) */
  w3 *= w4;
  /* #135: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #136: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #137: @1 = (@1*@4) */
  w1 *= w4;
  /* #138: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #139: @5 = (@5*@1) */
  w5 *= w1;
  /* #140: @26 = 00 */
  /* #141: @28 = vertcat(@21, @22, @23, @3, @5, @26) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w5;
  /* #142: @27 = @28[:2] */
  for (rr=w27, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #143: (@20[4:14:5] = @27) */
  for (rr=w20+4, ss=w27; rr!=w20+14; rr+=5) *rr = *ss++;
  /* #144: @29 = @20' */
  casadi_trans(w20,casadi_s3, w29, casadi_s2, iw);
  /* #145: @30 = project(@29) */
  casadi_project(w29, casadi_s2, w30, casadi_s4, w);
  /* #146: @31 = input[2][0] */
  casadi_copy(arg[2], 30, w31);
  /* #147: {@18, @17, @16, @15, @14} = horzsplit(@31) */
  casadi_copy(w31, 6, w18);
  casadi_copy(w31+6, 6, w17);
  casadi_copy(w31+12, 6, w16);
  casadi_copy(w31+18, 6, w15);
  casadi_copy(w31+24, 6, w14);
  /* #148: {NULL, NULL, NULL, @3, @5, @1} = vertsplit(@18) */
  w3 = w18[3];
  w5 = w18[4];
  w1 = w18[5];
  /* #149: @21 = 00 */
  /* #150: @22 = 00 */
  /* #151: @23 = 00 */
  /* #152: @25 = vertcat(@3, @5, @1, @21, @22, @23) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  /* #153: {NULL, NULL, NULL, @3, @5, @1} = vertsplit(@17) */
  w3 = w17[3];
  w5 = w17[4];
  w1 = w17[5];
  /* #154: @21 = 00 */
  /* #155: @22 = 00 */
  /* #156: @23 = 00 */
  /* #157: @24 = vertcat(@3, @5, @1, @21, @22, @23) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  /* #158: {NULL, NULL, NULL, @3, @5, @1} = vertsplit(@16) */
  w3 = w16[3];
  w5 = w16[4];
  w1 = w16[5];
  /* #159: @21 = 00 */
  /* #160: @22 = 00 */
  /* #161: @23 = 00 */
  /* #162: @32 = vertcat(@3, @5, @1, @21, @22, @23) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  /* #163: {NULL, NULL, NULL, @3, @5, @1} = vertsplit(@15) */
  w3 = w15[3];
  w5 = w15[4];
  w1 = w15[5];
  /* #164: @21 = 00 */
  /* #165: @22 = 00 */
  /* #166: @23 = 00 */
  /* #167: @33 = vertcat(@3, @5, @1, @21, @22, @23) */
  rr=w33;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  /* #168: {NULL, NULL, NULL, @3, @5, @1} = vertsplit(@14) */
  w3 = w14[3];
  w5 = w14[4];
  w1 = w14[5];
  /* #169: @21 = 00 */
  /* #170: @22 = 00 */
  /* #171: @23 = 00 */
  /* #172: @34 = vertcat(@3, @5, @1, @21, @22, @23) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w1;
  /* #173: @35 = horzcat(@25, @24, @32, @33, @34) */
  rr=w35;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #174: @36 = project(@35) */
  casadi_project(w35, casadi_s5, w36, casadi_s4, w);
  /* #175: @30 = (@30+@36) */
  for (i=0, rr=w30, cs=w36; i<28; ++i) (*rr++) += (*cs++);
  /* #176: output[2][0] = @30 */
  casadi_copy(w30, 28, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s11;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 237;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
