/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* Translational_drone_expl_ode_fun:(i0[6],i1[5],i2[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #7: @1 = input[1][3] */
  w1 = arg[1] ? arg[1][3] : 0;
  /* #8: @2 = (@0*@1) */
  w2  = (w0*w1);
  /* #9: @3 = input[1][2] */
  w3 = arg[1] ? arg[1][2] : 0;
  /* #10: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #11: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #12: @2 = (@2+@5) */
  w2 += w5;
  /* #13: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #14: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #15: @2 = (@2*@5) */
  w2 *= w5;
  /* #16: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #17: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #18: @0 = (@0*@3) */
  w0 *= w3;
  /* #19: @4 = (@4-@0) */
  w4 -= w0;
  /* #20: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #21: @4 = (@4*@5) */
  w4 *= w5;
  /* #22: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #23: @4 = 1 */
  w4 = 1.;
  /* #24: @0 = (2.*@3) */
  w0 = (2.* w3 );
  /* #25: @0 = (@0*@3) */
  w0 *= w3;
  /* #26: @4 = (@4-@0) */
  w4 -= w0;
  /* #27: @0 = (2.*@1) */
  w0 = (2.* w1 );
  /* #28: @0 = (@0*@1) */
  w0 *= w1;
  /* #29: @4 = (@4-@0) */
  w4 -= w0;
  /* #30: @4 = (@4*@5) */
  w4 *= w5;
  /* #31: @5 = 9.81 */
  w5 = 9.8100000000000005e+00;
  /* #32: @4 = (@4-@5) */
  w4 -= w5;
  /* #33: output[0][5] = @4 */
  if (res[0]) res[0][5] = w4;
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
