/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Translational_drone_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[12] = {6, 6, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[12] = {6, 6, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5};
static const casadi_int casadi_s2[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[3] = {2, 7, 11};
static const casadi_int casadi_s4[3] = {3, 8, 12};
static const casadi_int casadi_s5[21] = {6, 5, 0, 3, 5, 8, 11, 13, 3, 4, 5, 3, 4, 3, 4, 5, 3, 4, 5, 3, 4};
static const casadi_int casadi_s6[22] = {5, 6, 0, 0, 0, 0, 5, 10, 13, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 2, 3};
static const casadi_int casadi_s7[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s8[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s9[3] = {0, 0, 0};
static const casadi_int casadi_s10[3] = {6, 0, 0};

/* Translational_drone_impl_dae_fun_jac_x_xdot_u_z:(i0[6],i1[6],i2[5],i3[],i4[])->(o0[6],o1[6x6,3nz],o2[6x6,6nz],o3[6x5,13nz],o4[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+23, *w19=w+29, *w23=w+32, *w24=w+35, *w25=w+38, *w27=w+51, *w28=w+53, *w29=w+55;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #8: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #9: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #10: @3 = input[2][1] */
  w3 = arg[2] ? arg[2][1] : 0;
  /* #11: @4 = input[2][3] */
  w4 = arg[2] ? arg[2][3] : 0;
  /* #12: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #13: @7 = input[2][2] */
  w7 = arg[2] ? arg[2][2] : 0;
  /* #14: @8 = input[2][4] */
  w8 = arg[2] ? arg[2][4] : 0;
  /* #15: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #16: @5 = (@5+@9) */
  w5 += w9;
  /* #17: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #18: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #19: @10 = (@5*@9) */
  w10  = (w5*w9);
  /* #20: @11 = (@4*@8) */
  w11  = (w4*w8);
  /* #21: @12 = (@3*@7) */
  w12  = (w3*w7);
  /* #22: @11 = (@11-@12) */
  w11 -= w12;
  /* #23: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #24: @12 = (@11*@9) */
  w12  = (w11*w9);
  /* #25: @13 = 1 */
  w13 = 1.;
  /* #26: @14 = (2.*@7) */
  w14 = (2.* w7 );
  /* #27: @15 = (@14*@7) */
  w15  = (w14*w7);
  /* #28: @13 = (@13-@15) */
  w13 -= w15;
  /* #29: @15 = (2.*@4) */
  w15 = (2.* w4 );
  /* #30: @16 = (@15*@4) */
  w16  = (w15*w4);
  /* #31: @13 = (@13-@16) */
  w13 -= w16;
  /* #32: @16 = (@13*@9) */
  w16  = (w13*w9);
  /* #33: @17 = 9.81 */
  w17 = 9.8100000000000005e+00;
  /* #34: @16 = (@16-@17) */
  w16 -= w17;
  /* #35: @18 = vertcat(@0, @1, @2, @10, @12, @16) */
  rr=w18;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w16;
  /* #36: @6 = (@6-@18) */
  for (i=0, rr=w6, cs=w18; i<6; ++i) (*rr++) -= (*cs++);
  /* #37: output[0][0] = @6 */
  casadi_copy(w6, 6, res[0]);
  /* #38: @19 = zeros(6x6,3nz) */
  casadi_clear(w19, 3);
  /* #39: @6 = ones(6x1) */
  casadi_fill(w6, 6, 1.);
  /* #40: {NULL, NULL, NULL, @0, @1, @2} = vertsplit(@6) */
  w0 = w6[3];
  w1 = w6[4];
  w2 = w6[5];
  /* #41: @20 = 00 */
  /* #42: @21 = 00 */
  /* #43: @22 = 00 */
  /* #44: @23 = vertcat(@0, @1, @2, @20, @21, @22) */
  rr=w23;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #45: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #46: @24 = @23[:3] */
  for (rr=w24, ss=w23+0; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #47: (@19[:3] = @24) */
  for (rr=w19+0, ss=w24; rr!=w19+3; rr+=1) *rr = *ss++;
  /* #48: @24 = @19' */
  casadi_trans(w19,casadi_s1, w24, casadi_s0, iw);
  /* #49: output[1][0] = @24 */
  casadi_copy(w24, 3, res[1]);
  /* #50: @6 = zeros(6x6,6nz) */
  casadi_clear(w6, 6);
  /* #51: @18 = ones(6x1) */
  casadi_fill(w18, 6, 1.);
  /* #52: (@6[:6] = @18) */
  for (rr=w6+0, ss=w18; rr!=w6+6; rr+=1) *rr = *ss++;
  /* #53: @18 = @6' */
  casadi_trans(w6,casadi_s2, w18, casadi_s2, iw);
  /* #54: output[2][0] = @18 */
  casadi_copy(w18, 6, res[2]);
  /* #55: @25 = zeros(5x6,13nz) */
  casadi_clear(w25, 13);
  /* #56: @20 = 00 */
  /* #57: @21 = 00 */
  /* #58: @22 = 00 */
  /* #59: @0 = ones(5x1,1nz) */
  w0 = 1.;
  /* #60: {@1, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w1 = w0;
  /* #61: @5 = (@5*@1) */
  w5 *= w1;
  /* #62: @11 = (@11*@1) */
  w11 *= w1;
  /* #63: @13 = (@13*@1) */
  w13 *= w1;
  /* #64: @24 = vertcat(@20, @21, @22, @5, @11, @13) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w11;
  *rr++ = w13;
  /* #65: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #66: @19 = @24[:3] */
  for (rr=w19, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #67: (@25[:15:5] = @19) */
  for (rr=w25+0, ss=w19; rr!=w25+15; rr+=5) *rr = *ss++;
  /* #68: @20 = 00 */
  /* #69: @21 = 00 */
  /* #70: @22 = 00 */
  /* #71: @5 = ones(5x1,1nz) */
  w5 = 1.;
  /* #72: {NULL, @11, NULL, NULL, NULL} = vertsplit(@5) */
  w11 = w5;
  /* #73: @5 = (@4*@11) */
  w5  = (w4*w11);
  /* #74: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #75: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #76: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #77: @11 = (-@11) */
  w11 = (- w11 );
  /* #78: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #79: @11 = (@9*@11) */
  w11  = (w9*w11);
  /* #80: @26 = 00 */
  /* #81: @27 = vertcat(@20, @21, @22, @5, @11, @26) */
  rr=w27;
  *rr++ = w5;
  *rr++ = w11;
  /* #82: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #83: @28 = @27[:2] */
  for (rr=w28, ss=w27+0; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #84: (@25[1:11:5] = @28) */
  for (rr=w25+1, ss=w28; rr!=w25+11; rr+=5) *rr = *ss++;
  /* #85: @20 = 00 */
  /* #86: @21 = 00 */
  /* #87: @22 = 00 */
  /* #88: @5 = ones(5x1,1nz) */
  w5 = 1.;
  /* #89: {NULL, NULL, @11, NULL, NULL} = vertsplit(@5) */
  w11 = w5;
  /* #90: @5 = (@8*@11) */
  w5  = (w8*w11);
  /* #91: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #92: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #93: @13 = (@3*@11) */
  w13  = (w3*w11);
  /* #94: @13 = (-@13) */
  w13 = (- w13 );
  /* #95: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #96: @13 = (@9*@13) */
  w13  = (w9*w13);
  /* #97: @1 = (2.*@11) */
  w1 = (2.* w11 );
  /* #98: @1 = (@7*@1) */
  w1  = (w7*w1);
  /* #99: @14 = (@14*@11) */
  w14 *= w11;
  /* #100: @1 = (@1+@14) */
  w1 += w14;
  /* #101: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #102: @1 = (-@1) */
  w1 = (- w1 );
  /* #103: @19 = vertcat(@20, @21, @22, @5, @13, @1) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w13;
  *rr++ = w1;
  /* #104: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<3; ++i) *rr++ = (- *cs++ );
  /* #105: @24 = @19[:3] */
  for (rr=w24, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #106: (@25[2, 7, 11] = @24) */
  for (cii=casadi_s3, rr=w25, ss=w24; cii!=casadi_s3+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #107: @20 = 00 */
  /* #108: @21 = 00 */
  /* #109: @22 = 00 */
  /* #110: @5 = ones(5x1,1nz) */
  w5 = 1.;
  /* #111: {NULL, NULL, NULL, @13, NULL} = vertsplit(@5) */
  w13 = w5;
  /* #112: @3 = (@3*@13) */
  w3 *= w13;
  /* #113: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #114: @3 = (@9*@3) */
  w3  = (w9*w3);
  /* #115: @8 = (@8*@13) */
  w8 *= w13;
  /* #116: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #117: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #118: @5 = (2.*@13) */
  w5 = (2.* w13 );
  /* #119: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #120: @15 = (@15*@13) */
  w15 *= w13;
  /* #121: @5 = (@5+@15) */
  w5 += w15;
  /* #122: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #123: @5 = (-@5) */
  w5 = (- w5 );
  /* #124: @24 = vertcat(@20, @21, @22, @3, @8, @5) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w8;
  *rr++ = w5;
  /* #125: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #126: @19 = @24[:3] */
  for (rr=w19, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #127: (@25[3, 8, 12] = @19) */
  for (cii=casadi_s4, rr=w25, ss=w19; cii!=casadi_s4+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #128: @20 = 00 */
  /* #129: @21 = 00 */
  /* #130: @22 = 00 */
  /* #131: @3 = ones(5x1,1nz) */
  w3 = 1.;
  /* #132: {NULL, NULL, NULL, NULL, @8} = vertsplit(@3) */
  w8 = w3;
  /* #133: @7 = (@7*@8) */
  w7 *= w8;
  /* #134: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #135: @7 = (@9*@7) */
  w7  = (w9*w7);
  /* #136: @4 = (@4*@8) */
  w4 *= w8;
  /* #137: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #138: @9 = (@9*@4) */
  w9 *= w4;
  /* #139: @26 = 00 */
  /* #140: @28 = vertcat(@20, @21, @22, @7, @9, @26) */
  rr=w28;
  *rr++ = w7;
  *rr++ = w9;
  /* #141: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<2; ++i) *rr++ = (- *cs++ );
  /* #142: @27 = @28[:2] */
  for (rr=w27, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #143: (@25[4:14:5] = @27) */
  for (rr=w25+4, ss=w27; rr!=w25+14; rr+=5) *rr = *ss++;
  /* #144: @29 = @25' */
  casadi_trans(w25,casadi_s6, w29, casadi_s5, iw);
  /* #145: output[3][0] = @29 */
  casadi_copy(w29, 13, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Translational_drone_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Translational_drone_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Translational_drone_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s5;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Translational_drone_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 68;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
